# Generated by Django 4.2.2 on 2023-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form2', '0002_alter_professor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
